### ISSUE TITLE
TypeError when running a full analysis  

### ISSUE THREAD

**Issue by fkromer** [git-afsantos/haros_tutorials#1]
I tried to run the full analysis with haros v2.1.1 (installed via pypi) but I got the following error output:

```
$ haros full -p my_index.yaml
[HAROS] Loading common definitions...
[HAROS] Loading plugins...
[HAROS] Indexing source code...
[HAROS] Running analysis...
[HAROS] Saving analysis results...
Traceback (most recent call last):
  File "../haros/haros-runner.py", line 26, in <module>
    sys.exit(main(source_runner = True))
  File "/home/florian/ws_github/haros/haros/haros.py", line 608, in main
    if launcher.launch(argv = argv):
  File "/home/florian/ws_github/haros/haros/haros.py", line 138, in launch
    return args.command(args)
  File "/home/florian/ws_github/haros/haros/haros.py", line 155, in command_full
    return self.command_analyse(args) and self.command_viz(args)
  File "/home/florian/ws_github/haros/haros/haros.py", line 179, in command_viz
    if not os.path.isdir(args.data_dir):
  File "/usr/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

I am not sure if this relates to `haros` installed via pypi (more probable) or the setup in this repo. I run the example from [gavanderhoorn/haros_catkin_test](https://github.com/gavanderhoorn/haros_catkin_test) successfully already (with a [forked version of `haros`](https://github.com/gavanderhoorn/haros_catkin_test/blob/master/haros_test.rosinstall#L8)). Do you know about that one and the differences?

**Comment by git-afsantos** [comment]
That is a bug in v2.1.1. The `full` command fails when `-d` is not present. Thanks for reminding me of it. I uploaded v2.1.2, which fixes this issue. Let me know if you run into further problems.

**Comment by fkromer** [comment]
> I uploaded v2.1.2, which fixes this issue. Let me know if you run into further problems.

Thanks a lot!
